steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/realworld-app'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/realworld-app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - realworld-app
      - --image
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/realworld-app'
      - --region
      - '${_REGION}'
      - --platform
      - managed
      - --allow-unauthenticated
      - --service-account
      - 'aero-compte-service@aero-466808.iam.gserviceaccount.com'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/realworld-app'

substitutions:
  _REGION: europe-west9
  _REPO: realworld-repo

options:
  logging: CLOUD_LOGGING_ONLY

